### ISSUE TITLE
Паровоз 1-2-0 Дк 

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#10]
Двухпарка Коломенская.

Коломенский Тип 2 (1870-1874):

Цена: _10000$_
Вес: 33 т локомотив + _20 т тендер_
Скорость: 82 км/ч
Мощность: _300 ЛС_
ТУ: _30 кН_
СО; _3000$_
Срок службы: 35 лет

![Dk120_a1870](https://user-images.githubusercontent.com/89560412/146261516-cf8b83b0-6717-44a6-bf72-4074cea6ff32.png)

Коломенский Тип 9 (1875-1880):

Цена: _13000$_
Вес: 31 т локомотив + _20 т тендер_
Скорость: 75 км/ч
Мощность: _500 ЛС_
ТУ: _40 кН_
СО; _3000$_
Срок службы: 35 лет

![Dk120_a1875](https://user-images.githubusercontent.com/89560412/146261524-0e0df376-d65a-4975-94d2-7642c676c5d3.png)

**Comment by George-VB** [comment]
У многих спрайтов анимированные цвета. Надо пофиксить или указать, что нужен код с анимацией, как у ЭД4М

**Comment by SimozzzAK** [comment]
Цену скорректировать согласно таблицы:
Тип 2 (1870): с 28124 на ~10817
Тип 9 (1875): с 32812 на ~11829

**Comment by George-VB** [comment]
Что делать по задаче?
