### ISSUE TITLE
xUSSR Rails Bug: Trains using ELRL show up on unelectrified tracks.

### ISSUE THREAD

**Issue by Brickblock1** [George-VB/xussrset#105]
![Unnamed, 1970-01-01](https://user-images.githubusercontent.com/100433052/219779257-0f35f65c-0783-4732-b45d-ec218d85c1f3.png)

**Comment by George-VB** [comment]
Please provide a savegame

**Comment by Brickblock1** [comment]
[xussr rails, 1970-01-01.sav.txt](https://github.com/George-VB/xussrset/files/10824900/xussr.rails.1970-01-01.sav.txt)
Here I believe this happens with any selection of tracks.

**Comment by George-VB** [comment]
Fixed
