### ISSUE TITLE
Паровоз А 2-1-0 системы Крамптона

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#11]
Цена: 15000$
Вес: 31 т локомотив + 20 т тендер
Скорость: 82 км/ч
Мощность: 250 ЛС
ТУ: 20 кН
СО; 4000$ 
Срок службы: 25 лет

![A210](https://user-images.githubusercontent.com/89560412/146263169-46345a9f-0894-4f1c-ad3c-7befc68a79c8.png)

**Comment by George-VB** [comment]
Что даёт рефит? Он стоит денег? Срезание будки тоже стоит денег?

**Comment by SimozzzAK** [comment]
> Что даёт рефит? Он стоит денег? Срезание будки тоже стоит денег?

Рефит дает... будку?.. Как это отразится на характеристиках не знаю. Устанавливали для улучшения условий работы бригады.
По сути - eye candy. Можно бесплатным сделать.

**Comment by George-VB** [comment]
Проверить завод
Цена и Стоимость обслуживания огромные, особенно в сравнении с паровозом Д Шнайдера. Стоит провести ревизию стоимости обслуживания и цены всех паровозов, не представленных в таблице, и введённых по значениям.
Цвета для окраски RAL6002 и RAL6020, верно ли?
Установка будки стоит денег, но не даёт ничего.

**Comment by SimozzzAK** [comment]
СО в норме. Цена - нет.

В сете - 46874, в таблице 7392.

**Comment by George-VB** [comment]
Андрей, что мне надо делать по этой задаче?
