### ISSUE TITLE
Актуализировать сведения по ЭМВПС

### ISSUE THREAD

**Issue by George-VB** [George-VB/xussrset#110]
Провести актуализацию сведений по ЭМВПС

Тут написано https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D1%81%D1%82%D0%BE%D1%87%D0%BA%D0%B0_(%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BF%D0%BE%D0%B5%D0%B7%D0%B4)
что ЭС1 может быть расцеплен и дополнен прицепным вагоном без токоприёмника до 6-и вагонной составности
Значит его надо переделывать в конструктор.
Также вижу, что есть ЭС1П и ЭС2ПГ. И что производство закончено в 2022 году.
https://ru.wikipedia.org/wiki/%D0%AD%D0%9F%D1%80 тут написано, что ЭПр выпускался также в пятивагонной компоновке. Нужна актуализация

Также сверить составность. Она описана на странице, когда вносили в сет, этой информации не было

Также уточнить по ЭВС

**Comment by SimozzzAK** [comment]
ЭПр добавлен в 5-вагонной составности.
Остальные Штадлены в 0.9.

**Comment by SimozzzAK** [comment]
Для ЭС1 так и не было выпущено дополнительного прицепного, кроме того это потребует изменения окраски всех вагонов (из-за наклонных полос). Не делаем.
ЭС1П и ЭС2Г производство завершено. На смену "Ласточкам" поспешно делают серию из ЭС104/105/106 "Финист".

**Comment by SimozzzAK** [comment]
ЭВС так же прекращены поставки.
