### ISSUE TITLE
2ЭС7 + обновление 2ЭС10

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#118]
2ЭС7 в двух вариантах.
Предсерийный: один локомотив в 2013 и три в 2019.
Серийный; с 2020 года.

Так же выпущенным с 2020 года 2ЭС10 - маска идентична 2ЭС7.

**Comment by George-VB** [comment]
Нужна проверка свойств

**Comment by SimozzzAK** [comment]
Физические свойства корректны.

Цены и СО следует отдельно ребалансировать по всему ПС. Это в 0.9.
