### ISSUE TITLE
Обновление Т (Тк)

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#12]
Трехпарка Коломенская.
Сейчас в наборе как Паровоз Т (0-3-0)
Добавить индекс к Т - Тк.

Новая модификация.

Коломенский Тип 1 (1870-1875):

Цена: 10000$
Вес: 32 т локомотив + 20 т тендер
Скорость: 52 км/ч
Мощность: _310 ЛС_
ТУ: _30 кН_
СО; 3200$
Срок службы: 40 лет

![tk030_a1870](https://user-images.githubusercontent.com/89560412/146263909-4ed91374-92dc-49a0-ac31-faced90eabe4.png)

**Comment by George-VB** [comment]
Tk - 1-1-1
Tᴷ - 0-3-0

**Comment by George-VB** [comment]
Не сделан тендер, требует исправления графики
Какие-то бешенные Цена и СО по сравнению с им же, но 1875 года. В 3 раза цена, в 6 раз СО. Тоже пока не стал делать

**Comment by SimozzzAK** [comment]
Тендер есть в файле (не на месте) и аналогичен А Крамптона.
