### ISSUE TITLE
Обновление графики ЧС2

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#137]
Добавление новых окрасок.

**Comment by SimozzzAK** [comment]
Варианты:
1) Заводской, доступен до 1972.
2) Заводской с полосами, принудительная перекраска для 1 в 1972.
3) Аврора/Россия (Дневной Экспресс), доступна всегда.
4) RAL 7010 (62), доступна для перекраски с 1972.
5) RAL 5023 (9D), доступна для перекраски с 1972.
6) ТЧЭ-27 Орёл-Сортировочный, доступна для перекраски с 2003 года.
7) УЗ (корпоративная), доступка для перекраски с ~2020 (точны год не известен?) года.

**Comment by SimozzzAK** [comment]
Добавлена графика ЧС2К ЯРЗ.
Доступна как платный рефит с 2002 года для ЧС2 Е53.

**Comment by StarscreamKng** [comment]
8. ЧС2К ЗЭРЗ
9. УЗ (ТЧ-2 Харьков-Главное) для ЧС2 и ЧС2К (ЗЭРЗ)

**Comment by SimozzzAK** [comment]
Эти варианты не были предоставлены, так что отдельной задачей в 0.9.
