### ISSUE TITLE
ЭП2Д добавить ливрею цппк 

### ISSUE THREAD

**Issue by AliceAllst** [George-VB/xussrset#14]
доступна с 2015 года через переоборудование 
Central Passanger Suburban Company Центрально Пригородная Пассажирская Компания

Использовать файлы 
ep2d_h-CPPK.png
ep2d_m-CPPK.png
ep2d_c-CPPK.png

Добавить ее в код ливрей

**Comment by SimozzzAK** [comment]
![image](https://user-images.githubusercontent.com/89560412/197899830-dce8a862-8c46-4342-8a7f-83eb560e6954.png)
Спрайт головы обрезан.
