### ISSUE TITLE
Обеспечить унификацию выбора графики по году постройки через шаблон

### ISSUE THREAD

**Issue by George-VB** [George-VB/xussrset#15]
В ЭД4М выявлено в головном вагоне использован код шаблона
engine_build_year2_template(ed4m_h, 2010, 2012, left, )
engine_build_year2_template(ed4m_h, 2010, 2012, right, )
а в прицепных нет
switch (FEAT_TRAINS, SELF, ed4m_m_direction_left,
  (build_year >= 2010) +
  (build_year >= 2012))
{
  0: ed4m_m_b2010_direction_left;
  1: ed4m_m_a2010_direction_left;
     ed4m_m_a2012_direction_left;
}
Привести к единому виду, также проверить аналогичный ПС

**Comment by SimozzzAK** [comment]
У вагона 1912 правильным считается что построенным после 1918 года (формально не должны быть доступны, выпуск вагона до 1917 года) есть одинаковые внешне окраски для рефита в заводскую и в 6020?
У ДР1А - немоторный головной доступен в 1991, а окрасы для других вагонов появляются только с 1995.
РА1 - все в норме. Осталось только графику для предсерийного (1998 года) сделать.
ЭД4М - у  построенных после 2010 года голова до формирования состава развернута не в ту сторону

**Comment by George-VB** [comment]
> У вагона 1912 правильным считается что построенным после 1918 года (формально не должны быть доступны, выпуск вагона до 1917 года) есть одинаковые внешне окраски для рефита в заводскую и в 6020?
fixed

> У ДР1А - немоторный головной доступен в 1991, а окрасы для других вагонов появляются только с 1995.
так и должно быть

> РА1 - все в норме. Осталось только графику для предсерийного (1998 года) сделать. 
ок

> ЭД4М - у построенных после 2010 года голова до формирования состава развернута не в ту сторону
fixed
