### ISSUE TITLE
Добавление графики грузов для открытых вагонов.

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#17]
Добавление графики STEL-Slab, COPR-Coil, Alum-Ingot для платформ и полувагонов 5, 6, 8 и 9 шаблонов.

Stel-slab - Стальной сляб, грубая заготовка для дальнейшей переплавки или обработки. Подойдет как графика для STEL, IRON, METL, CSTI, STAL, STCB, STST.

COPR-Coil - Медь в рулонах. Подойдет как графика для COPR, POWR, STSH, STWR

ALUM-Ingot - Аллюминиевые слитки. Подойдет как графика для ALUM, METL, ZINK

**Comment by George-VB** [comment]
STSH, STWR,  ZINK - нет таких грузов
Есть  ZINС, это не то же самое?

**Comment by SimozzzAK** [comment]
Steel Sections - STSE - Металлоконструкции - Штучный
Steel Sheet - STSH - Листовая сталь - Штучный
Steel Wire Rod - STWR - Стальная проволока - Штучный

Грузы из FIRS 4.4.0 Steel Town.
В последней версии нет этих грузов, хотя графика есть. 

ZINK - да, опечатка.

**Comment by SimozzzAK** [comment]
STSE - графика stel-frames и goods в ящиках, например в 9м шаблоне goods-2, goods-3, goods-4. Соотношение 5/1/1/1.
STSH - графика stel-sheet, stel-sheet-cup, stel-coil, stel-coil-cup. Соотношение равное.
STWR - графика stel-v-coil и goods в ящиках.  Соотношение 5/1/1/1.

**Comment by SimozzzAK** [comment]
ALUM - графика stel-alum-ingot

**Comment by George-VB** [comment]
Сделан 8 и 9 шаблон, можно пока их проверить

**Comment by George-VB** [comment]
Остался alum
