### ISSUE TITLE
Криовагоны для кислорода: 2-осный обр 1932г., 8Г52, 15-558С-04

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#18]
https://scaletrainsclub.com/board/viewtopic.php?style=5&f=46&t=3501&start=50
Три вагона для перевозки сжиженного кислорода:
2-осный, обр. 1935 года.
8Г52, обр 1953-1955 года.
15-558С-04 обр. 2015 года. https://vagon.by/model/15-558%D0%A1-04

Информации по ним мало, поскольку кислород в больших объемах как правило был необходим в военно-космической отрасли.
В промежутке 1955-2015 было еще две цистерны: 8Г512 и 8Г513.

**Comment by SimozzzAK** [comment]
В крытых до 11-К251.

**2-осный 1932 года** 
В основе платформа грузоподъемностью 20т.

Цена: _5000 $_
СО: _100 $/год_
Вес _16 т_.
Скорость: _100 км/ч_
Грузоподъемность 13.5 т
Может перевозить: O2__
Объём _12 м3._
Скорости погрузки и разгрузки - низкие (2 ед/тик).
Выпуск 1932-1955
Производитель - _Мариупольский завод_
Цвета как у крытых: 48, 6A, 6C, 61.


**8Г52**

Цена: _14000 $_
СО: _800 $/год_
Вес 38 т.
Скорость: _100 км/ч_
Грузоподъемность 34 т
Может перевозить: O2__, RFPR, FORM
Объём _30 м3._
Скорости погрузки и разгрузки - низкие (4 ед/тик).
Выпуск 1953-... 
Производитель - Мариупольский завод, Уралкриомаш (дочка УВЗ, может вместо УВЗ оставить?).

**15-558С-04**

Цена: _25000 $_
СО: _400 $/год_
Вес 35 т.
Скорость: _120 км/ч_
Грузоподъемность 57 т
Может перевозить: O2__, RFPR
Объём 49 м3.
Выпуск 2014-...
Производитель - Уралкриомаш (дочка УВЗ, может вместо УВЗ оставить?).

**Comment by SimozzzAK** [comment]
Цвета для 15-558С-04
08, 09

**Comment by George-VB** [comment]
Не указаны сроки службы.
15-558С-04 он точно не 15-558S-04 ?
Уточнить типы грузов (см #50)
