### ISSUE TITLE
окрас др1а уз с 1999

### ISSUE THREAD

**Issue by maxhoroshko** [George-VB/xussrset#191]
![dr1a-type1976_c-part2 (1)](https://github.com/George-VB/xussrset/assets/47902651/167d7ccb-6606-4fbd-a95e-6a34c0895ff9)
![dr1a-type1976_h-part2](https://github.com/George-VB/xussrset/assets/47902651/c96b9b5a-b793-4e31-9009-195d221e29b9)

**Comment by StarscreamKng** [comment]
Недостаёт двух альтернативных ливрей УЗ для ДР1А, извиняюсь за длинные ссылки:
1. https://ru.wikipedia.org/wiki/%D0%94%D0%A01#/media/%D0%A4%D0%B0%D0%B9%D0%BB:%D0%94%D0%B8%D0%B7%D0%B5%D0%BB%D1%8C-%D0%BF%D0%BE%D0%B5%D0%B7%D0%B4_%D0%94%D0%A01%D0%90_%D0%9A%D0%B8%D0%B5%D0%B2-%D0%94%D0%BD%D0%B5%D0%BF%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_%D0%B4%D0%B5%D0%BF%D0%BE_%D0%92%D1%8B%D1%88%D0%B3%D0%BE%D1%80%D0%BE%D0%B4_P7264223.JPG
2. ливрея ДР1Ам https://ru.wikipedia.org/wiki/%D0%94%D0%A01#/media/%D0%A4%D0%B0%D0%B9%D0%BB:DR1Am-197_diesel_trainset_2013_G1.jpg

**Comment by SimozzzAK** [comment]
По текущей окраске замечаний нет. Другие окраски - другой задачей и в 0.9.
