### ISSUE TITLE
61-817 добавление окрасов УЗ-бренд/UZ-brand,УЗ-бренд1/UZ-brand1,УЗ-бренд2/UZ-brand2  

### ISSUE THREAD

**Issue by maxhoroshko** [George-VB/xussrset#194]
61-817, окрасы доступны с 2020 как отдельный рефит
название УЗ-бренд/UZ-brand,УЗ-бренд1/UZ-brand1,УЗ-бренд2/UZ-brand2 доступны для вагонов 61-817 c 2020 года
![61-817-part3](https://github.com/George-VB/xussrset/assets/47902651/f34a8524-ce48-4fd9-845d-4f35b21a9f55)

**Comment by George-VB** [comment]
![image](https://github.com/George-VB/xussrset/assets/43310520/3caf7656-14c4-4597-9ba3-8b741eb61316)
