### ISSUE TITLE
ЧС4квр добавление окраса UZ-brand/УЗ-бренд после 2022

### ISSUE THREAD

**Issue by maxhoroshko** [George-VB/xussrset#195]
ЧС4квр,окрас доступен с 2022 как отдельный рефит название UZ-brand/УЗ-бренд лоступен для ЧС4квр после 2022
![chs4z-part2](https://github.com/George-VB/xussrset/assets/47902651/a69e1250-8c11-41f1-ab56-8d45ee3220f5)

**Comment by George-VB** [comment]
Название ливреи сделано УЖД
