### ISSUE TITLE
ЧС8 новый рефит УЗ-новая-ливрея/UZ-new-livery после 2022

### ISSUE THREAD

**Issue by maxhoroshko** [George-VB/xussrset#197]
ЧС8,окрас доступен с 2022 как отдельный рефит название УЗ-новая-ливрея/UZ-new-livery доступен для ЧС8 после 2022
![chs8-part3](https://github.com/George-VB/xussrset/assets/47902651/c93ecab6-52f1-4e81-b37f-150b25d7f829)

**Comment by George-VB** [comment]
Название ливреи сделано УЖД
