### ISSUE TITLE
Цистерна для растительных масел 15-1219-1П

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#25]
https://vagon.by/model/15-1219-1%D0%9F

Цена: _9000 $_
СО: _200 $/год_
Вес 23 т.
Скорость: 120 км/ч
Грузоподъемность 69 т
Может перевозить: cargo_all_food_tanker
Объём 83 м3.
Скорости погрузки и разгрузки - низкие (2 ед/тик).
Выпуск 2019(2020?)-...
Производитель - Рузаевский завод химического машиностроения
Цвета как у крытых: 48, 6A, 6C, 61.

**Comment by George-VB** [comment]
Подозрительно низкая цена, втрое ниже аналогов
