### ISSUE TITLE
Думпкар 4ВС-50

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#27]
https://vagon.by/model/4%D0%92%D0%A1-50

Цена: _5000 $_
СО: _350 $/год_
Вес 31 т.
Скорость: 80 км/ч 
Грузоподъемность 50 т
Может перевозить: cargo_all_bulklist
Объём 23 м3.
Выпуск 1959-1969
Производитель - Калининградский вагоностроительный завод
Цвета: 7B, 71, 72, 4B, 02, 03 .6A, 21.

**Comment by George-VB** [comment]
Откуда информация об ограничении скорости в 80 км/ч? В таблице 120
