### ISSUE TITLE
Думпкар 6ВС60 (31-638)

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#30]
Две графики: до 1978 и с 1978 (только нововыпущеным)

https://scaletrainsclub.com/board/viewtopic.php?f=46&t=7859

https://vagon.by/railcars/compare/583/584

Цена: _5000_ $
СО: 375 $/год
Вес 26 т.
Скорость: 120 км/ч (груженым до 80?)
Грузоподъемность 60 т
Может перевозить: cargo_all_bulklist
Объём 26 м3.
Выпуск 1971-1988
Производитель - Калининградский вагоностроительный завод, Демиховский машиностроительный завод.
Цвета: 7B, 71, 72, 4B, 02, 03 .6A, 21.

**Comment by George-VB** [comment]
> Скорость: 120 км/ч (груженым до 80?)
Это к кому вопрос. По таблице у этой модели нет снижения скорости для гружёных.
