### ISSUE TITLE
Добавить ДТ1 в сет

### ISSUE THREAD

**Issue by AliceAllst** [George-VB/xussrset#48]
Добавить файлы графики в нужное расположение
Написать код для ДТ1 

При написание кода учесть: 
Составности:
Г+М+Г; Г+М+П+Г 
Дизель-электропоезд может эксплуатироваться по СМЕ 

Технические данные
--
Род службы	пассажирский (пригородный), служебный
Составность 3—4 (либо 6—8 по СМЕ)
Г+М+Г:
Г+М+П+Г;
(Г+М+Г) + (Г+М+Г)
(Г+М+П+Г) + (Г+М+Г)
(Г+М+П+Г) + (Г+М+П+Г)

Техничесские данные брать из таблички (62-9003) ЭТ4А

**Comment by George-VB** [comment]
А почему он электропоезд, если он Дт?

**Comment by SimozzzAK** [comment]
Выхлоп не с той стороны вагона идет.
