### ISSUE TITLE
Уточнить раскладку груза по цистернам

### ISSUE THREAD

**Issue by George-VB** [George-VB/xussrset#50]
Определить, какие вагоны должны иметь какие типы (для агрегирующих типов)
Вопрос вызван задачей #18 на создание вагонов по перевозке кислорода. По иерархии многие вагоны получают возможность перевозки кислорода, например вагоны образца 1931 и 1945 годов, которые имеют список грузов cargo_all_tanker()

![image](https://user-images.githubusercontent.com/43310520/182401739-44072040-76ba-4a4f-a5cb-ac3247a42cd5.png)

Очевидно, что для общих вагонов необходимо делать существенные ограничения на ёмкость специализированных грузов, иначе они на единицу длины состава окажутся выгоднее специализированных, либо сужать список перевозимых в таких вагонов грузов.

Необходимо учитывать нюанс, что сделать очень низкую вместимость особого груза в нетиповом вагоне (например жидкости в крытом вагоне) очень просто, а в типовом (другой цистерне) значительно сложнее.

**Comment by George-VB** [comment]
Заодно хорошо бы в расчёте СО учитывать расходы на обогрев и т.п, как это сделано у рефов.

**Comment by George-VB** [comment]
И заодно проверить tanker_refit_cost на предмет корректности групп "мойки" танков

**Comment by SimozzzAK** [comment]
Перевозка не типовых грузов в цистернах (как кислорода) не должна осуществляться. Если для грузов нет подходящих цистерн - в крытыв со штрафом к вметсимости (по нормативам кислородные баллоны должны укладываться лежа и не более чем в 2 слоя, если правильно помню).

Что касается грузов для цистерн, то делить стоит на 3 глобальные категории: 
Жидкости (Liquid), газы (новая, Gas(eous)) и сыпучие (Bulk, сейчас Cement).

Жидкости делить на пищевые и не пищевые.

Пищевые жидкости на термосы (Молоко, продукты) и простые (Вода, Спиртное и т.д).

Непищевые на нефтяные и химические.

Нефтяные на светлые (Химикаты, Бензин) и темные нефтепродукты (те что с подогревом, для сырой нефти и нефтепродуктов).

Химические на простые (каучук, краски) и опасные (сера, кислоты и т.д.).

Газовые цистерны на криогенные (кислород, аргон, азот), и химические (хлор, аммиак и т.д.).

Сыпучие цистерны во многом идентичны крытым хопперам.




tl:dr
Из той схемы выделить отдельно газовые цистерны. Перенести в них как химические CHLO, NITR., как крио O2__.

В случае с криоцистернами, их приспосабливали ещё и под формалин, что подходит под описание RFPR.

**Comment by George-VB** [comment]
![image](https://user-images.githubusercontent.com/43310520/184556193-130eb971-7134-4702-9c07-ce68136815ff.png)

**Comment by SimozzzAK** [comment]
![image](https://user-images.githubusercontent.com/89560412/209871684-eb5174b3-db2c-4f74-8127-4fc35c8615e0.png)

Обновлена таблица грузов для всех категорий.
