### ISSUE TITLE
ЭШ2: Невозможно присоединить второй состав

### ISSUE THREAD

**Issue by Rau117** [George-VB/xussrset#64]
При попытке подключить два любых состава вылазит ошибка «невозможно переместить, требуется моторный вагон без токоприёмника».

Нижний «поезд» – попытка обмануть игру, сначала собрать состав, а потом удалить вагон перед поездом. Проблема та же – «моторный без токопр.»
![изображение](https://user-images.githubusercontent.com/47086324/185481775-8521e51a-a2a4-419a-9208-4854dcb15737.png)

**Comment by George-VB** [comment]
Исправлено, проверяй, если всё хорошо - закрывай
