### ISSUE TITLE
СО (V-КП-2)

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#8]
СО, промышленный электровоз постоянного тока 750 В.

https://ru.wikipedia.org/wiki/%D0%A1%D0%9E_(%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%B2%D0%BE%D0%B7)
http://rusrailmodel.ru/img/scheme/SO/co_1.jpg

На фото ниже электровоз В в сплотке с IV-КП1А. V-КП2 так же эксплуатировался в ММК. Похоже что электровозы на 750 В спокойно и на 1500 В себя там чувствуют.
https://trainpix.org/photo/307452/

Характеристики:
Цена: _80000$_
Вес: 94т
Скорость: 65 км/ч
Мощность: 880-1000кВт по двигателям - _~975 ЛС на рельсах_
ТУ: 18т - 182кН
Стоймость обслуживания: 3000$/год
Выпуск: 1936-1941
Срок службы: 30 лет
Тип: Электровоз промышленный постоянного (1,5кВ) тока.
СМЕ: нет
Производитель: «Динамо», Подольский крекинго-электровозостроительный, Коломенский

Шаблон 8 (симметричный с одним пантографом, шаблона нет)
![SO](https://user-images.githubusercontent.com/89560412/131454917-4d69e639-8c5e-4291-b055-128ed1d26600.png)

**Comment by George-VB** [comment]
Нужны пояснения, чем первый вид отличается от второго и когда каждый из них применять?
Или в графике ошибка, и второй ряд должен быть с поднятым пантографом с выключенными фонарями, идти вторым в сме?

**Comment by SimozzzAK** [comment]
В сплотке пантограф только у первого поднят, другие нет (а должны).

**Comment by SimozzzAK** [comment]
При этом искрят. Т.е. что-то не так.

**Comment by George-VB** [comment]
Проблема вызвана ошибкой в графике. Во втором ряду (локомотив под током не в начале поезда) нарисованы опущенные пантографы.
