### ISSUE TITLE
Сделать доступными все устаревшие ливреи после 2050 года

### ISSUE THREAD

**Issue by Rau117** [George-VB/xussrset#83]
Основная проблема – после 2016 года многие локомотивы меняют заводскую раскраску на корпоративную pıd (ржд), становясь однообразными и слабо различимы в масштабе openttd. Решение – вернуть возможность перекраски вне рамок «реалистичной» игры – после 2050 года. 

Для каждого локомотива включить все ему доступные раскраски.
----
Тепловозы

- ТЭП60 (+)
- ТЭП70 (+)
- ТЭП70БС (+)
- 2ТЭ116 (+)
- ТЭМ7А (+)
- ТЭ3 (+)

Электровозы

- 2ЭС4К (+)
- 2ЭС10 (+)
- 2ЭС6 (+)
- 3ЭС5К (+)
- Э5К (+)
- 2ЭС5К (+)
- ЭП2К (+)
- ЧС2 (+)
- ВЛ8 (+)

ЭМВПС

- ЭД4М (+)

**Comment by George-VB** [comment]
В задаче необходимо указать список ПС, для которых это необходимо сделать
Группами по типам (тепловозы, электровозы, т.д)

**Comment by Rau117** [comment]
Решено использованием групп #98
