### ISSUE TITLE
Вагоны для природного газа (категории gas_natural_tanker)

### ISSUE THREAD

**Issue by SimozzzAK** [George-VB/xussrset#91]
Как и другие спец-грузы до 1960х - в крытых вагонах со штрафом.

902R
https://vagon.by/model/902%D0%A0

903R
https://vagon.by/model/903%D0%A0/626

908R
https://vagon.by/model/908%D0%A0

15-1208 (9 шаблон!)
https://vagon.by/model/15-1208

Цвета как у других газовых цистерн. Отличие в красной полосе (нарисована).

**Comment by George-VB** [comment]
А цена? А стоимость эксплуатации?
