### ISSUE TITLE
Provide support for Variations

### ISSUE THREAD

**Issue by George-VB** [George-VB/xussrset#98]

**Comment by SimozzzAK** [comment]
Для тестирования следует выбрать серии наподобии *ТЭ10* или М62.
Проверить как себя ведет на разных локомотивах с разными временами появления.

Кроме того - протиражировать на все сборные МВПС

**Comment by SimozzzAK** [comment]
Версия от 1:14, 4705

Замечания:
ДПКР2 туалет не объединен с другими вагонами.

Вагоны ДР1 объединить вместе как и другие ДР1*

Предложения:
Объединить Ээл и Ээл2.

Объединить М62, ДМ62, 2М62, 2М62У и 3М62У общей надгруппой.

Объединить 2ТЭ10Ут и 2ТЭ10Ут-К.

Объединить ТЭ10, 2ТЭ10 и 2ТЭ40. Позже в группу добавить ТЭ3Л.

ТЭП60 объединить с 2ТЭП60.

2ТЭ10* можно все объединить вместе общей надгруппой. Объединить СМЕ для 2ТЭ10В и 2ТЭ10Л. 2ТЭ10М-К сделать рефитом для 2ТЭ10В и 2ТЭ10Л.

Объединить ЧС2 и ЧС2Т.

Объединить Сс и Си.

Объединить ЧС4 и ЧС4Т.

Объединить ВЛ65, ЭП1, ЭП1М, ЭП1П.

Объединить 2ЭС5 и 2ЭС5С.

Объединить все ЭР9 общей надгруппой.


Паровозы надо рассмотреть отдельно, т.к. в них много вариантов сходу не видно.

**Comment by SimozzzAK** [comment]
Для определения формата дальнейших переделок в вариации взял ранние пассажирские паровозы. Заодно добавил Ну (верхний индекс) что внешне схож с Нв.

В случае с группами где даты не пересекаются - использовать данные последнего появившегося для сортировки.

В случае Д:
1867 - 1874: параметры Д Шнейдера Тип 66
1875 - 1880: параметры Дк Тип 9

В случае У/Уу:
Визуальное отличие в тендере.
Отличия У от Уу в увеличенной мощности и массе паровоза (У - 72 т, Уу - 76 т). Точных данных по мощности нет. Предлагаю за Уу принять текущий У с мощностью 1100 лс, а нового У снизить мощность до 1000 лс. Не модификация, только новопостроенным паровозам.


```
А (2-1-0)

Д	{
	Д Шнейдера
		{
		Тип 66 (0-2-1) 1867-1877
		}
	Дк Коломенский	
		{
		Тип 2 (1-2-0) 1870-1874
		Тип 9 (1-2-0) 1875-1880
		}
	}
	
Н	{
	Нд	
		{
		Тип 53 (1-3-0) 1892-1896
		Тип 67 (1-3-0) 1897-1902
		}
	Нв
		{
		Тип 90 (1-3-0) 1903-1909
		}
	!Ну (графика от Нв, отличия от Нв: мощность 790 лс, ТУ 81 кН)
		{
		Усиленный (1-3-0) 1910-1912
		}
	}
	
Ж (2-3-0)

У	{
	У (Нефтяной тендер) 1906-1911
	У (Угольный тендер) 1909-1911 (3 осный, тот что короче)
	Уу (Нефтяной тендер) 1912
	Уу (Угольный тендер) 1912 (4 осный)
	}
```


Интересует насколько удобно текущее отображение. И стоит ли выделять новый ПС, не требующий графики, в отдельные задачи?

**Comment by SimozzzAK** [comment]
Дальнейшая разбивка пассажирских паровозов. Интересно как себя поведут в промежутках выпуска, как на том же С. Все идут подряд (и те что не требуют разбивки). // - те что требуют новую графику (убирать не стал, задачи на них будут сформирванны отдельно).


Паровозы серии С 
	{
	1910-1919 Паровоз С (1-3-1)
	\\1913-1915 Паровоз Св (1-3-1) Тип 145
	1924-1929 Паровоз Су(1-3-1) Тип 152
	\\1926-1930 Паровоз Су(1-3-1) Тип 153
	1932-1936 Паровоз Су(1-3-1) Тип 162
	1936-1940 Паровоз Су(1-3-1) Тип 163
	\\1939-1940 Паровоз Сум(1-3-1) Тип П16 
	\\1940-1941  Паровоз Сум(1-3-1) Тип П19 
	1947-1951	 Паровоз Су(1-3-1)
	\\1948 Паровоз Сур (1-3-1) 
	
Паровозы серии Л (2-3-1)

Паровозы серии ИС (1-4-2)
	{
	1932-1935 ИС 20 (Коломенский завод, 4-осный тендер)
	1936-1941 ИС 20	(Ворошиловоградский завод, 6-осный тендер)
	\\1938 - ИС 20-16 (с обтекателем)
	1941-1942 ИС 21
	}
Паровоз П12 (2-3-2 К)

Паровозы серии П36 (2-4-2)
	{
	\\1950 - П36-0001 (Прототип)
	1953-1956 П36
	}
